### PR TITLE
UI improvements

### LINKED ISSUE #24: option for years months days hours minutes
While it's nice to have days hours, etc, not so much after you have over 1000 days.
It's much more readable if there was an option for years, months, days, hours seconds.

Personally i don't even need exact months since one is 28 days and others are 30 or 31, but it would be nice for the crazy exact people.

### PR DESCRIPTION
**Pull request by unbiaseduser**
I have made some qol improvements on various parts of the ui:
- Use Material components instead of regular Android components. _If you want to implement Material You theme later, you pretty much have to use them._ Also, as I explained earlier, **_you don't have to avoid it_** and they simply look nicer.
- Fix toolbar not showing on light mode.
- Fix a bug where you can pick a future time in today.
- The date formatting now expands to years, months and weeks. Also, if any time unit is 0, it's hidden. Fixes #24 
- The Create activity is more optimized for one handed usage. (all elements are positioned lower).

### CODE REVIEW

**Comment by unbiaseduser** [comment]
Hold on a sec. _**Please wait for me to fix time formatting, it's harder than I thought.**_

**Comment by unbiaseduser** [comment]
Everything should be ok now, feel free to ask questions

**Comment by KiARC** [comment]
I'm merging without checks because they don't want to run, I really hope there's no build issues.

**Comment by KiARC** [comment]
Crap

**Comment by KiARC** [comment]
fixed it

**Pull request merged**
