### PR TITLE
Add Import and Export

### PR DESCRIPTION
**Pull request by cubandle**
Redo of #70 on the new codebase

### CODE REVIEW

**Comment by KiARC** [comment]
Oh perfect!

**Comment by cubandle** [comment]
I will try to apply the old version of this feature (manual serialization) to v7.0.0
I think it's only necessary to backport the export feature.

**Comment by KiARC** [comment]
True true. Thanks so much

**Comment by cubandle** [comment]
I created 2 branches on my fork: v8.0.0_export and v7.0.0_export. I was thinking maybe the best way to do this is to generate apks for a few past releases and then allow users to install them from an announcement. I wasn't able to test if this approach works because I don't know how to create signed apks. Could you test this to see if this approach works? (Something like install v8.0.0, then signed apk from v8.0.0_export). Also, do you know if it matters if the app was installed from F-Droid vs APK? Thanks

**Comment by KiARC** [comment]
I'll figure it out, thank you so so much

**Comment by KiARC** [comment]
@cubandle Small issue,the v7.0.0_export branch is based on v8.0.0 I think. Could you check?

**Comment by cubandle** [comment]
I'm really sorry, I don't know how that happened. I recreated the v7.0.0_export branch and I think it's right now.

I can also work on past versions as well. How many versions back should we go?

**Comment by KiARC** [comment]
I think most people are likely on 7 and 8 so this is good, thanks so much!

**Comment by cubandle** [comment]
Hi Kat, I don't mean to rush you, but do you still plan to release a v7.0.0_export apk?

**Comment by KiARC** [comment]
Some time soon sorry, I have some big stuff I need to deal with. I'm gonna be on a hiatus for a few months most likely, because of mental health treatment. Sorry. I'll be back as soon as I'm able to be.

**Comment by cubandle** [comment]
That's fine take your time!

**Pull request merged**
