### PR TITLE
Pull in "I'm Definitely Sober"

### PR DESCRIPTION
**Pull request by KiARC**
I love your tweaks, and I'm gonna work on merging them into the main app. Thank you so much!

### CODE REVIEW

**Comment by KiARC** [comment]
@unbiaseduser Is it possible we could work on removing the fact that you changed the package, icon etc so I can properly merge this?

**Comment by KiARC** [comment]
I'm gonna have to do this manually

**Comment by unbiaseduser** [comment]
I'd like to, but i don't actually know how to do it correctly

**Comment by KiARC** [comment]
I'm working on it

**Comment by KiARC** [comment]
Please going forwards don't just change the name and logo of the app, especially the package name, I get that I'm working slowly and that's because I'm in high school and just don't have time but that was very not cool

**Comment by KiARC** [comment]
Makes it very very hard to merge

**Comment by unbiaseduser** [comment]
I'm sorry
I was actually reimplementing everything from scratch on the regular branch tho, I was just about to be done

**Comment by KiARC** [comment]
Then please do that /nm

**Comment by KiARC** [comment]
That'll help a lot

**Pull request closed without merging**
